
GET http://localhost:4000/health

###

POST http://localhost:4000
Content-Type: application/json

{
    "name": "Tamim",
    "country": "BD",
    "rank": 1
}

### 

GET http://localhost:4000

###
GET http://localhost:4000/718-YjxY_

###
GET http://localhost:4000/JCSb2X3MM

###
PATCH http://localhost:4000/CpBwT2sk-
Content-Type: application/json

{
    "name": "Rajib"
}

###
PUT http://localhost:4000/5j610h1JM
Content-Type: application/json

{
    "name": "Rounok Hasan",
    "country": "BD",
    "rank": 2
}

###
PUT http://localhost:4000/TpL4O2zsK
Content-Type: application/json

{
    "name": "Sajib",
    "country": "BD",
    "rank": 10
}

###
DELETE http://localhost:4000/7_HzGHLWI
Content-Type: application/json

{
    "name": "Barfy11",
    "country": "BD",
    "rank": 10
}